# Generated by Django 5.2.4 on 2025-07-25 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blog_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='product_image',
            new_name='blog_image',
        ),
    ]
